--- #YAML:1.0
name:                Sol-Parser
version:             0.01
abstract:            a .sol file reader
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    File::Find:                    0
    Log::Log4perl:                 0
    Test::Differences:             0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Andreas Faafeng <aff@cpan.org>
